### PR TITLE
Responsive CSS and color variables.

### PR DESCRIPTION
**Pull request by Coiot**
Changed all the px instances for flexible ems and rems that change the design based on the screen size and the root font size. Have also changed all the colors to correspond with the root color variables which will allow for easier user customization.

### CODE REVIEW

**Comment by neauoire** [comment]
What the WHAT?! I didn't even know you could do that in CSS?!

**Comment by neauoire** [comment]
FFUUCK that broke the look of the page :/ It looks awful on my end. The font-size especially.

**Comment by neauoire** [comment]
I won't revert but I'll have to fix that CSS stuff, one moment..

**Comment by neauoire** [comment]
I had to revert, sorry :( It looked all fucked up on Safari. I really liked the colour variables, but the spacing was all broken for me.
screen shot 2017-10-18 at 6 56 18 am

**Comment by Coiot** [comment]
Interesting. I don't see an error on my end but I'll review to see if there
is not some rogue semi-colon causing trouble or something.

**Comment by Coiot** [comment]
No worries. The strategy to have all the spacing dependent on the root font
size certainly then makes it all dependent on the initial variable to keep
the design responsive. Individual values through the sheet would have to be
changed to suit the desired margins. You are welcome to keep the color
variables tho in other areas of your CSS, as it will not interfere with any
spacing.

**Pull request merged**
